apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "myapp=777777777777777/myflaskpyapp:latest"
    argocd-image-updater.argoproj.io/write-back-method: none
spec:
  project: default
  source:
    repoURL: 'https://your-dummy-repo-url-for-structure.com'
    path: deploy
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: macedonsky777
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
