#metadata:
#  annotations:
#    argocd-image-updater.argoproj.io/image-list: "myapp=777777777777777/myflaskpyapp"
#    argocd-image-updater.argoproj.io/mycontainer.update-strategy: latest
#    argocd-image-updater.argoproj.io/myalias.force-update: "true"
#    argocd-image-updater.argoproj.io/yourtool.allow-tags: regexp:^v1.0.0-[0-9a-zA-Z]+$
#    syncOptions:
#      - Replace=true  # Заміна існуючих ресурсів при синхронізації
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myflaskpyapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/macedonsky777/argotest.git'
    targetRevision: HEAD
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: macedonsky777
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
