apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myflaskpyapp-ingress
  namespace: macedonsky777
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - app.macedonsky777-cluster.watashinoheyadesu.pp.ua
    secretName: myflaskpyapp-tls
  rules:
  - host: app.macedonsky777-cluster.watashinoheyadesu.pp.ua
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myflaskpyapp-service
            port:
              number: 80
