apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskpyapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskpyapp
  template:
    metadata:
      labels:
        app: myflaskpyapp
    spec:
      containers:
      - name: myflaskpyapp
        image: 777777777777777/myflaskpyapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
